apiVersion: v1
kind: Service
metadata:
  name: petclinic
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: petclinic
